######################################################################
# Automatically generated by qmake (3.1) Tue Mar 8 02:04:01 2022
######################################################################

QT += widgets core gui
TEMPLATE = app
TARGET = test2
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

DEFINES += QCUSTOMPLOT_USE_LIBRARY

CONFIG(debug, release|debug) {
win32:QCPLIB = qcustomplotd2
else: QCPLIB = qcustomplotd
} else {
win32:QCPLIB = qcustomplot2
else: QCPLIB = qcustomplot
}
LIBS += -L. -l$$QCPLIB

# Input
SOURCES += main.cpp
